// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func IndexPage(name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><title>Millemetri</title><meta name=\"description\" content=\"Storia, arte e cultura di Cercemaggiore\"><!-- Facebook Meta Tags --><meta property=\"og:url\" content=\"https://millemetri.net/\"><meta property=\"og:type\" content=\"website\"><meta property=\"og:title\" content=\"Millemetri\"><meta property=\"og:description\" content=\"Storia, arte e cultura di Cercemaggiore\"><meta property=\"og:image\" content=\"https://millemetri.net/static/millemetri-og.jpg\"><!-- Twitter Meta Tags --><meta name=\"twitter:card\" content=\"summary_large_image\"><meta property=\"twitter:domain\" content=\"millemetri.net\"><meta property=\"twitter:url\" content=\"https://millemetri.net/\"><meta name=\"twitter:title\" content=\"Millemetri\"><meta name=\"twitter:description\" content=\"Storia, arte e cultura di Cercemaggiore\"><meta name=\"twitter:image\" content=\"https://millemetri.net/static/millemetri-og.jpg\"><link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/static/apple-touch-icon.png\"><link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/static/favicon-32x32.png\"><link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/static/favicon-16x16.png\"><link rel=\"manifest\" href=\"/static/site.webmanifest\"><meta name=\"msapplication-TileColor\" content=\"#da532c\"><meta name=\"theme-color\" content=\"#ffffff\"><link rel=\"stylesheet\" href=\"/static/style.css\"></head><body class=\"bg-orange-50 flex items-center justify-center\"><div class=\"w-2/3 md:w-1/2 lg:w-1/3\"><img src=\"/static/millemetri-logo.svg\" alt=\"Millemetri - La rivista di Cercemaggiore\"></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
